    </div>


    <div class-"row">
        <div id="footer" class="col-xs-12">
            <p>Web-site development using the MVC design pattern and the Bootstrap CSS framework</p>
        </div>
    </div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
</body>
</html>