<?php require('template/header.phtml') ?>

    <div class="container">
        <header class="header">Change Password</header>
        <div class="my-3 p-3 bg-white rounded box-shadow">
            <div class="form">
                <div class = "form-group">
                    <input type="password" name="password" id="password" class="form-control"
                           placeholder="Enter password">
                </div>
                <div class = "form-group">
                    <input type="password" name="password" id="password" class="form-control"
                           placeholder="Confirm Password">
                </div>
                <input type="submit" name="changePassword" class="btn btn-primary" value="Confirm">
            </div>
        </div>
    </div>
<?php require('template/footer.phtml') ?>