<?php require('template/header.phtml') ?>

    <div class="container">
        <header class="header">Change Password</header>
        <div class="my-3 p-3 bg-white rounded box-shadow">
            <form action = "../changePassword.php" method = "post">
                <div class="form">
                    <div class = "form-group">
                        <input type="password" name="password" class="form-control" placeholder="Enter password">
                    </div>
                    <div class = "form-group">
                        <input type="password" name="confirmPassword" class="form-control" placeholder="Confirm Password">
                    </div>
                </div>
                <input type="submit" name="changePassword" class="btn btn-primary" value="Confirm">
            </form>
        </div>
    </div>
    <?php if(isset($view->message)) : ?>
        <div class="alert alert-dark" role="alert"><?= $view->message ?></div>
    <?php endif; ?>
<?php require('template/footer.phtml') ?>