<?php require_once('template/header.phtml'); ?>



    <div class="container">
        <header class="header">Account Management</header>
        <div class="row createAcc">
            <form class="col" method="post" action="../createAcc.php">
                <h4>Unavailability</h4>
                <div class="form-group">
                    <label for="listView">Select User</label>
                    <select name="selectedUser" id = "listView">
                        <?php foreach ($view->users as $user) :?>
                        <option value = "<?= $user->getUsername()?>"> <?= $user->getUsername() ?></option>
                        <?php endforeach ; ?>
                    </select>
                </div>
                <div class="form-group">
                    <label for="datepicker">Select Start Date</label>
                    <input type="text" id="datepicker" class="form-control" name="startDate" readonly="true">
                </div>
                <div class="form-group">
                    <label for="datepicker2">Select End Date</label>
                    <input type="text" id="datepicker2" class="form-control" name="endDate" readonly="true">
                </div>
                <button type="submit" class="btn btn-success" name="unavailabilitySubmit">Submit</button>
            </form>
            <form class="col" method="get" action="../createAcc.php">
                <div class="form-group">
                    <label for="listView">Select User</label>
                    <select name="username" id = "listView" onchange="this.form.submit()">
                        <?php foreach ($view->users as $user) :?>
                            <option value = "<?= $user->getUsername()?>" <?php if(isset($_GET["username"]) && $_GET["username"] == $user->getUsername()) echo "selected = '" . $user->getUsername() . "''"?>> <?= $user->getUsername() ?></option>
                        <?php endforeach ; ?>
                    </select>
                </div>
            </form>
            <div class = col id = "unavailabilityList">
                <?php if(isset($view->unavailability)) :?>
                    <?php foreach ($view->unavailability as $UnavailabilityData) : ?>
                        <div class="card my-3">
                            <div class="card-body">
                                <h5 class="card-title">
                                    <?= date('d/m/Y',strtotime($UnavailabilityData->getDateStart())); ?> ---
                                    <?= date('d/m/Y',strtotime($UnavailabilityData->getDateEnd())); ?>
                                </h5>
                            </div>
                            <div>
                                <form method="post" action="../createAcc.php?username=<?=$_GET["username"]?>">
                                    <button class="btn-primary" name="delete" value="<?=$UnavailabilityData->getId()?>">Delete</button>
                                </form>
                            </div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
        </div>
        <div class="row createTeam">
            <form class="col" method="post" action="../createAcc.php">
                <h4>Create Account</h4>
                <div class="form-group">
                    <label for="exampleInputUsername">Username</label>
                    <input type="text" class="form-control" id="exampleInputUsername" placeholder="Username" name="username">
                    <small class="form-text text-muted">We'll never share your details with anyone else.</small>
                </div>
                <div class="form-group">
                    <label for="listView">Select Team</label>
                    <select name="selectedTeam" id = "listView">
                        <?php foreach ($view->teams as $team) :?>
                            <option value = "<?= $team->getTeamName()?>"> <?= $team->getTeamName() ?></option>
                        <?php endforeach ; ?>
                    </select>
                </div>
                <div class="form-group">
                    <label for="listView">Select Developer Type</label>
                    <select name="selectedDev" id = "listView">
                        <option value ="Admin">Admin</option>
                        <option value ="Developer">Developer</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="listView">Select Developer Experience</label>
                    <select name="selectedExp" id = "listView">
                        <option value ="Junior">Junior</option>
                        <option value ="Experienced">Experienced</option>
                        <option value ="Senior">Senior</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-success" name="createUserSubmit">Submit</button>
            </form>
            <form class="col" method="post" action="../createAcc.php">
                <h4>Create Team</h4>
                <div class="form-group">
                    <label for="inputTeamName">Team Name</label>
                    <input type="text" class="form-control" id="inputTeamName" placeholder="Team Name" name="teamName">
                </div>
                <button type="submit" class="btn btn-success" name="createTeamSubmit">Create Team</button>
            </form>
        </div>
        <?php if(isset($view->message)) : ?>
            <div class="alert alert-dark" role="alert"><?= $view->message ?></div>
        <?php endif; ?>
    </div>
<?php require_once('template/footer.phtml'); ?>