<?php require_once('template/header.phtml'); ?>

<body>
<div class="container">
    <header class="header">Support Rota</header>
    <div class="row">




        <div class="col-xl-12">
            <div class="my-3 p-3 bg-white rounded box-shadow">

                <h2 id="currentDate">Current date: <?= date("d/m/Y") ?></h2>

                <div class="card my-3">
                    <div class="card-body">
                        <h5 class="card-title">14/02/19 --- 28/02/19</h5>
                        <div class="users text-center">
                            <span class="badge badge-pill badge-primary">Luke Wood</span>
                            <span class="badge badge-pill badge-primary">Omar Farrah</span>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">29/02/19 --- 14/03/19</h5>
                        <div class="users text-center">
                            <span class="badge badge-pill badge-primary">Aaron Gagan</span>
                            <span class="badge badge-pill badge-primary">Josh Watson<span>
                        </div>
                    </div>
                </div>


            </div>
        </div>



    </div>
</div>
</body>

<?php require_once('template/footer.phtml'); ?>
