<?php require_once('template/header.phtml'); ?>

<div class="container">
    <header class="header">Support Rota</header>
    <div class="row">
        <div class="col-xl-12">
            <div class="my-3 p-3 bg-white rounded box-shadow">

                <h2 id="currentDate">Current date: <?= date("d/m/Y") ?></h2>

                <div class="card my-3">
                    <div class="card-body">
                        <h5 class="card-title">14/02/20 --- 28/02/20</h5>
                        <div class="users text-center">
                            <span class="btn btn-primary">Luke Wood</span>
                            <span class="btn btn-primary">Omar Farrah</span>
                        </div>
                    </div>
                </div>

                <div class="card my-3">
                    <div class="card-body">
                        <h5 class="card-title">29/02/20 --- 14/03/20</h5>
                        <div class="users text-center">
                            <span class="btn btn-primary">Aaron Gagan</span>
                            <span class="btn btn-primary">Josh Watson<span>
                        </div>
                    </div>
                </div>

                <div class="card my-3">
                    <div class="card-body">
                        <h5 class="card-title">15/03/20 --- 30/03/20</h5>
                        <div class="users text-center">
                            <span class="btn btn-primary">Jimmy Jimson</span>
                            <span class="btn btn-primary">Billy Bilson<span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
<?php require_once('template/footer.phtml'); ?>
