<?php require_once('template/header.phtml'); ?>

<div class="container">
    <header class="header">Support Rota</header>
    <div class="row">
        <div class="col-xl-12">
            <div class="my-3 p-3 bg-white rounded box-shadow">

                <h2 id="currentDate">Current date: <?= date("d/m/Y") ?></h2>

                <?php foreach ($view->supportRota as $supportTeam) : ?>
                    <div class="card my-3">
                        <div class="card-body">
                            <h5 class="card-title"><?=$supportTeam->getDateStart()?> --- <?=$supportTeam->getDateEnd()?></h5>
                            <div class="users text-center">
                                <span class="btn btn-primary"><?=$supportTeam->getDeveloper1()?></span>
                                <span class="btn btn-primary"><?=$supportTeam->getDeveloper2()?></span>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>
</body>

<?php require_once('template/footer.phtml'); ?>
