<?php require_once('template/header.phtml') ?>
<body>
<div class="container">
    <header class="header">Maintenance Screen</header>
    <div class="row">
        <div class="col-xl-6" id="supportTeamColumn">
            <?php $index = 0 ?>
            <?php foreach ($view->supportTeams as $team): ?>
                <div class="card my-3" id="supportTeam">
                    <div class="card-header" id="dates">
                        <h5><span id="startDate"><?= $team->getDateStart() ?></span>
                            ---
                            <span id="endDate"><?= $team->getDateEnd() ?></span>
                        </h5>
                        <button onclick="">Get available devs</button>
                    </div>
                    <div class="card-body">
                        <div class="dev droppableRotaSlot" id="rotaSlot<?= ++$index ?>">
                            <p class="card-text" id="originalDev<?= $index ?>">
                                <span id="originalDeveloperName"><?= $team->getDeveloper1() ?></span>
                                <button class='trashButtonOriginalDev'
                                        onclick='removeDeveloperFromSupport(<?= $index ?>)'><i
                                            class='fas fa-trash-alt'></i></button>
                                <?php if (!$view->unavailabilityObject->checkAvailability($team->getDeveloper1(), $team->getDateStart(), $team->getDateEnd())): ?>
                                    <script>
                                        document.getElementById("rotaSlot" + <?= $index ?>).style.backgroundColor = "red";
                                    </script>
                                <?php endif; ?>
                            </p>
                        </div>
                        <div class="dev droppableRotaSlot" id="rotaSlot<?= ++$index ?>">
                            <p class="card-text" id="originalDev<?= $index ?>">
                                <span id="originalDeveloperName"><?= $team->getDeveloper2() ?></span>
                                <button class='trashButtonOriginalDev'
                                        onclick='removeDeveloperFromSupport(<?= $index ?>)'><i
                                            class='fas fa-trash-alt'></i></button>
                            </p>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
            <button onclick="updateRota()">Save modified rota</button>
        </div>

        <div class="col-xl-6" id="developerTeamColumn">
            <?php foreach ($view->developerTeams as $team): ?>
            <div class="card my-3">
                <div class="card-header">
                    <h5><?= $team->getTeamName() ?></h5>
                </div>
                <div class="card-body">
                    <?php $users = $view->developerTeamObject->getDevelopers($team->getTeamName()) ?>
                    <?php $userIndex = 0 ?>
                    <?php foreach ($users as $user): ?>
                        <div class="dev draggableDevelopers" id="devCard<?= ++$index ?>">
                            <p class="card-text" id="devCardText<?= $index ?>">
                                <span id="devCardName"><?= $user->getUsername() ?></span>
                                <!-- Button here -->
                            </p>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</body>
<?php require_once('template/footer.phtml') ?>
