<?php require_once('template/header.phtml') ?>

    <body>
    <div class="container">
        <header class="header">Maintenance Screen</header>
        <div class="row">
            <div class="col-xl-6">
                <?php $index = 0 ?>
                <?php foreach ($view->supportTeams as $team): ?>
                    <div class="card my-3">
                        <div class="card-header">
                            <h5><?= date("d/m/y", strtotime($team->getDateStart())) ?>
                                ---
                                <?= date("d/m/y", strtotime($team->getDateEnd())) ?>
                            </h5>
                        </div>
                        <div class="card-body">
                            <div class="dev droppableRotaSlot" id="rotaSlot<?= ++$index ?>">
                                <p class="card-text" id="originalDev<?= $index ?>">
                                </p>
                            </div>
                            <script type="text/javascript">
                                var name = "<?= $team->getDeveloper1() ?>";
                                document.getElementById("originalDev<?= $index ?>").innerHTML = name + "<button class='trashButtonOriginalDev' onclick='removeOriginalDevFromSupport(<?= $index ?>)'><i class='fas fa-trash-alt'></i></button>";
                            </script>
                            <div class="dev droppableRotaSlot" id="rotaSlot<?= ++$index ?>">
                                <p class="card-text" id="originalDev<?= $index ?>">
                                </p>
                            </div>
                            <script type="text/javascript">
                                var name = "<?= $team->getDeveloper2() ?>";
                                document.getElementById("originalDev<?= $index ?>").innerHTML = name + "<button class='trashButtonOriginalDev' onclick='removeOriginalDevFromSupport(<?= $index ?>)'><i class='fas fa-trash-alt'></i></button>";
                            </script>
                        </div>
                    </div>
                <?php endforeach; ?>
                <button>Save modified rota</button>
            </div>

            <div class="col-xl-6">
                <?php foreach ($view->developerTeams as $team): ?>
                <div class="card my-3">
                    <div class="card-header">
                        <h5><?= $team->getTeamName() ?></h5>
                    </div>
                    <div class="card-body">
                        <?php $users = $view->developerTeamObject->getDevelopers($team->getTeamName()) ?>
                        <?php $userIndex = 0 ?>
                        <?php foreach ($users as $user): ?>
                            <div class="dev draggableDevelopers" id="devCard<?= ++$index ?>">
                                <p class="card-text" id="devCardText<?= $index ?>">
                                    <span id="devCardName"><?= $user->getUsername() ?></span>
                                    <button class="trashButton" id="trash<?= $index ?>"
                                            onclick="removeDeveloperFromSupport(<?= $index ?>)"><i
                                                class="fas fa-trash-alt"></i>trash
                                    </button>
                                </p>
                            </div>
                        <?php endforeach; ?>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </body>

<?php require_once('template/footer.phtml') ?><?php
