<?php if(isset($_SESSION["user"]) && $_SESSION["type"] == "admin"){?>
<?php require_once('template/header.phtml'); ?>

<div class="container">
    <header class="header">Team Management</header>
    <div class="row createTeam">
        <form class="col-xl-6" method="post" action="../teamManagement.php">
            <h4>Team Unavailability</h4>
            <div class="form-group">
                <label for="listView">Select Team</label>
                <select name="selectedTeam" id = "listView">
                    <?php foreach ($view->teams as $team) :?>
                        <option value = "<?= $team->getTeamName()?>"> <?= $team->getTeamName() ?></option>
                    <?php endforeach ; ?>
                </select>
            </div>
            <div class="form-group">
                <label for="datepicker">Select Start Date</label>
                <input type="text" id="datepicker" class="form-control" name="startDate" readonly="true">
            </div>
            <div class="form-group">
                <label for="datepicker2">Select End Date</label>
                <input type="text" id="datepicker2" class="form-control" name="endDate" readonly="true">
            </div>
            <button type="submit" class="btn btn-success" name="unavailabilitySubmit">Submit</button>
        </form>
    </div>
    <div class="row createTeam">
        <form class="col-xl-6" method="post" action="../userManagement.php">
            <h4>Create Team</h4>
            <div class="form-group">
                <label for="inputTeamName">Team Name</label>
                <input type="text" class="form-control" id="inputTeamName" placeholder="Team Name" name="teamName">
            </div>
            <button type="submit" class="btn btn-success" name="createTeamSubmit">Create Team</button>
        </form>
    </div>
    <?php if(isset($view->message)) : ?>
        <div class="alert alert-dark" role="alert"><?= $view->message ?></div>
    <?php endif; ?>
</div>

<?php require_once('template/footer.phtml'); }?>
