<?php if(isset($_SESSION["user"]) && $_SESSION["type"] == "admin"){?>
<?php require_once('template/header.phtml'); ?>

    <div class="container">
        <header class="header">User Management</header>
        <div class="row createAcc">
            <div class = "col">
                <h4>Set Unavailability</h4>
                <div class="form-group">
                    <form method="get" action="../userManagement.php">
                        <div class="form-group">
                            <label for="username">Search user</label>
                            <input id="username" name="username">
                            <?php
                            $names = [];
                            foreach ($view->users as $user)
                            {
                                array_push($names, $user->getUsername());
                            }
                            ?>
                            <script>
                                $(function() {
                                    $("#username").autocomplete({
                                        source: <?= json_encode($names) ?>
                                    });
                                });
                            </script>
                            <button onclick="this.form.submit()">View user</button>
                        </div>
                    </form>
                </div>
                <form method="post" action="../userManagement.php?username=<?=$_GET["username"];?>">
                    <div class="form-group">
                        <label for="datepicker">Select Start Date</label>
                        <input type="text" id="datepicker" class="form-control" name="startDate" readonly="true">
                    </div>
                    <div class="form-group">
                        <label for="datepicker2">Select End Date</label>
                        <input type="text" id="datepicker2" class="form-control" name="endDate" readonly="true">
                    </div>
                    <button type="submit" class="btn btn-success" name="unavailabilitySubmit">Submit</button>
                </form>
            </div>
            <div class = "col">
                <div id = "unavailabilityList">
                    <?php if(isset($view->unavailability)) :?>
                        <h4>User Unavailability: </h4>
                        <?php foreach ($view->unavailability as $UnavailabilityData) : ?>
                            <div class="card my-3 text-center">
                                <div class="card-body">
                                    <h5 class="card-title">
                                        <?= date('d/m/Y',strtotime($UnavailabilityData->getDateStart())); ?> ---
                                        <?= date('d/m/Y',strtotime($UnavailabilityData->getDateEnd())); ?>
                                    </h5>
                                </div>
                                <div>
                                    <form method="post" action="../userManagement.php?username=<?=$_GET["username"]?>">
                                        <button class="btn btn-danger" name="delete" value="<?=$UnavailabilityData->getId()?>">Delete</button>
                                    </form>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <div class="row createUser mt-5">
            <form class="col" method="post" action="../userManagement.php">
                <h4>Create Account</h4>
                <div class="form-group">
                    <label for="exampleInputUsername">Username</label>
                    <input type="text" class="form-control" id="exampleInputUsername" placeholder="Username" name="username">
                    <small class="form-text text-muted">We'll never share your details with anyone else.</small>
                </div>
                <div class="form-group">
                    <label for="listView">Select Team</label>
                    <select name="selectedTeam" id = "listView">
                        <?php foreach ($view->teams as $team) :?>
                            <option value = "<?= $team->getTeamName()?>"> <?= $team->getTeamName() ?></option>
                        <?php endforeach ; ?>
                    </select>
                </div>
                <div class="form-group">
                    <label for="listView">Select Developer Type</label>
                    <select name="selectedDev" id = "listView">
                        <option value ="Admin">Admin</option>
                        <option value ="Developer" selected>Developer</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="listView">Select Developer Experience</label>
                    <select name="selectedExp" id = "listView">
                        <option value ="Junior">Junior</option>
                        <option value ="Experienced">Experienced</option>
                        <option value ="Senior">Senior</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-success" name="createUserSubmit">Submit</button>
            </form>

            <div class="col">
                <?php if (isset($view->userDetails) && $view->userDetails->getUsername() != "") :?>
                <h4>User Details: </h4>
                <div class="card text-center">
                    <h5 class="card-header"><?= $view->userDetails->getUsername(); ?></h5>
                    <div class="card-body">
                        <form method="post">
                            <div class="form-group">
                                <label for="updatedDevTeam" class="text-dark"><b>Dev team: </b></label>
                                <select name="updatedDevTeam" id="updatedDevTeam">
                                    <?php foreach($view->teams as $team) :?>
                                        <option value="<?=$team->getTeamName();?>" <?php if($view->userDetails->getDevTeam() == $team->getTeamName()){echo "selected";}?> > <?= $team->getTeamName(); ?></option>
                                    <?php endforeach;?>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="listView" class="text-dark"><b>Developer type: </b></label>
                                <select name="updatedDevExp" id = "listView">
                                    <option value ="Junior" <?php if($view->userDetails->getExperience() == "Junior") echo "selected"; ?>>Junior</option>
                                    <option value ="Experienced" <?php if($view->userDetails->getExperience() == "Experienced") echo "selected"; ?>>Experienced</option>
                                    <option value ="Senior" <?php if($view->userDetails->getExperience() == "Senior") echo "selected"; ?>>Senior</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <button class="btn btn-warning mr-5" type="submit" value="<?= $view->userDetails->getUsername(); ?>" name="updateUser">Update</button>
                                <button class ="btn btn-danger" type="submit" value="<?= $view->userDetails->getUsername(); ?>" name="deleteUser">Delete</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <?php endif ;?>
        </div>
        <?php if(isset($view->message)) : ?>
            <div class="row alert alert-dark col-12 mt-3" role="alert"><?= $view->message ?></div>
        <?php endif; ?>
    </div>

<?php require_once('template/footer.phtml'); } ?>