<?php require('template/header.phtml') ?>
    <div class="container">
        <header class="header">Your Support Team Dates</header>
        <div class="row">


            <div class="col-xl-12">
                <div class="my-3 p-3 bg-white rounded box-shadow">
                    <h2 id="currentDate">Current date: <?= date("d/m/Y") ?></h2>

                    <div class="card my-3">
                        <div class="card-body">
                            <h5 class="card-title">14/02/20 --- 28/02/20</h5>
                            <div class="users text-center">
                                <span class="btn btn-primary">Luke Wood</span>
                                <span class="btn btn-primary">Omar Farrah</span>
                            </div>
                        </div>
                    </div>

                    <div class="card my-3">
                        <div class="card-body">
                            <h5 class="card-title">1/04/20 --- 15/04/20</h5>
                            <div class="users text-center">
                                <span class="btn btn-primary">Luke Wood</span>
                                <span class="btn btn-primary">Josh Watson<span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </body>
<?php require('template/footer.phtml') ?>