<?php require('template/header.phtml') ?>
    <div class="container">
        <header class="header">Your Support Team Dates</header>
        <div class="row">
            <div class="col-xl-12">
                <div class="my-3 p-3 bg-white rounded box-shadow">
                    <h2 id="currentDate">Current date: <?= date("d/m/Y") ?></h2>
                    <?php foreach ($view->rota as $rota) : ?>
                        <div class="card my-3">
                            <div class="card-body">
                                <h5 class="card-title"><?=$rota->getDateStart()?> --- <?=$rota->getDateEnd()?></h5>
                                <div class="users text-center">
                                    <span class="btn btn-primary"><?=$rota->getDeveloper1()?></span>
                                    <span class="btn btn-primary"><?=$rota->getDeveloper2()?></span>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
    </body>
<?php require('template/footer.phtml') ?>
